[package]
name = "safer-ffi-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
safer-ffi-gen-macro = { path = "../safer-ffi-gen-macro/"}
safer-ffi = { version = "0.0.10", features = ["proc_macros", "out-refs"] }

[dev-dependencies]
trybuild = "1"

[[example]]
name = "basic_usage"
