# This is a basic workflow to notify in Slack of new pull requests.

name: Pull Request Slack Notifier

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "pr_link": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "user_alias": "${{github.event.pull_request.user.login}}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
